class Configuration:

	APOLLO_DIRECTORY = '/home/epimetheus/Documents/apollo/'
	DELPHI_DIRECTORY = '/home/epimetheus/Documents/delphi/'

	ALERTS_DIRECTORY = DELPHI_DIRECTORY + 'alerts/'
	ANALYSIS_DIRECTORY = DELPHI_DIRECTORY + 'analysis/'
	CATALOGS_DIRECTORY = DELPHI_DIRECTORY + 'catalogs/'
	LOGS_DIRECTORY = DELPHI_DIRECTORY + 'logs/'

	ALERTS_GW_DIRECTORY = ALERTS_DIRECTORY + 'gw/'
	ALERTS_GW_JSON_DIRECTORY = ALERTS_GW_DIRECTORY + 'json/'
	ALERTS_GW_MOC_DIRECTORY = ALERTS_GW_DIRECTORY + 'moc/'
	ALERTS_GW_PARAM_DIRECTORY = ALERTS_GW_DIRECTORY + 'param/'
	ALERTS_GW_SKYMAP_DIRECTORY = ALERTS_GW_DIRECTORY + 'skymap/'

	ANALYSIS_SURVEY_DIRECTORY = ANALYSIS_DIRECTORY + 'survey/'
	ANALYSIS_GW_DIRECTORY = ANALYSIS_DIRECTORY + 'gw/'
	ANALYSIS_GW_FIELDS_DIRECTORY = ANALYSIS_GW_DIRECTORY + 'fields/'
	ANALYSIS_GW_GALAXIES_DIRECTORY = ANALYSIS_GW_DIRECTORY + 'galaxies/'

	DELPHI_DIRECTORIES = [DELPHI_DIRECTORY,
							ALERTS_DIRECTORY,
							ANALYSIS_DIRECTORY,
							CATALOGS_DIRECTORY,
							LOGS_DIRECTORY,
							ALERTS_GW_DIRECTORY, 
							ALERTS_GW_JSON_DIRECTORY,
							ALERTS_GW_MOC_DIRECTORY,
							ALERTS_GW_PARAM_DIRECTORY, 
							ALERTS_GW_SKYMAP_DIRECTORY,
							ANALYSIS_SURVEY_DIRECTORY,
							ANALYSIS_GW_DIRECTORY, 
							ANALYSIS_GW_FIELDS_DIRECTORY,
							ANALYSIS_GW_GALAXIES_DIRECTORY]

	CATALOG = 'glade+'
	EXPOSURE_TIME = 300.
	FIELD_PRIORITY = ['commissioning', 'ligo', 'science', 'main_survey']
	GALACTIC_PLANE = 15.
	GALAXY_LIMIT = 50
	MOON_DISTANCE = 60.
	OBSERVATORY = 'oafa'
	OVERHEAD = 30.
	READ_TIME = 100.

	CLIENT_ID = 'j1hrnlcur5mc2mkch0a037s98'
	CLIENT_SECRET = '1ojbdiie5bl6ccsf369b74hk0v0lcuemaeq32r4qa9dor9up4cp0'
	EMAIL = 'toros.alerts@yahoo.com'
	MAILING_LIST = ['rcamuccio@gmail.com', 'moises.castillo01@utrgv.edu', 'moemyself3@gmail.com']
	PAS = 'ncnrlqwdthofhoch'
	PORT = 465
	SMTP = 'smtp.mail.yahoo.com'